<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>GLSH.Backend.Glsl</AssemblyName>
    <RootNamespace>DVG.Shaders.Backend.Glsl</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\\GLSH.Compiler\\GLSH.Compiler.csproj" />
  </ItemGroup>
</Project>
