<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>Delta.Shader.Analyzers</RootNamespace>
    <IsPackable>false</IsPackable>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <IncludeSymbols>false</IncludeSymbols>
    <EnableNETAnalyzers>false</EnableNETAnalyzers>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\\Delta.Shader.Backend.Glsl\\Delta.Shader.Backend.Glsl.csproj" />
    <ProjectReference Include="..\\Delta.Shader.Compiler\\Delta.Shader.Compiler.csproj" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" />
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>

  <Target Name="CopyDeltaShaderAnalyzerDependencies" AfterTargets="Build">
    <Copy SourceFiles="@(ReferenceCopyLocalPaths)" DestinationFolder="$(TargetDir)" SkipUnchangedFiles="true" />
  </Target>
</Project>
