<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <NoWarn>$(NoWarn);EnableGenerateDocumentationFile</NoWarn>
    <Deterministic>true</Deterministic>
    <PathMap>$(MSBuildThisFileDirectory)=/src/</PathMap>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <AnalysisMode>Recommended</AnalysisMode>
  </PropertyGroup>

  <PropertyGroup Condition="$(MSBuildProjectName.StartsWith('DeltaShader'))">
    <RepositoryUrl>https://github.com/Artromskiy/DeltaShader</RepositoryUrl>
    <Authors>DeltaShader contributors</Authors>
  </PropertyGroup>
  <ItemGroup>
    <AdditionalFiles Include="$(MSBuildThisFileDirectory)CodeMetricsConfig.txt" />
  </ItemGroup>
</Project>
