<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Delta.Shader.Text</RootNamespace>
    <AssemblyName>DeltaShader.Text</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <DeltaShaderEnabled>true</DeltaShaderEnabled>
  </PropertyGroup>

  <ItemGroup>
    <DeltaShaderSource Include="Shaders/**/*.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DeltaShader.Contract\DeltaShader.Contract.csproj" />
    <ProjectReference Include="..\DeltaShader\DeltaShader.csproj" />
    <ProjectReference Include="..\DeltaShader.Analyzers\DeltaShader.Analyzers.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <Analyzer Include="..\DeltaShader.Analyzers\bin\$(Configuration)\netstandard2.0\DeltaShader.Analyzers.dll" />
    <Analyzer Include="..\DeltaShader\bin\$(Configuration)\netstandard2.0\DeltaShader.dll" />
    <Analyzer Include="..\DeltaShader.Compiler\bin\$(Configuration)\netstandard2.0\DeltaShader.Compiler.dll" />
    <Analyzer Include="..\DeltaShader.Backend.Glsl\bin\$(Configuration)\netstandard2.0\DeltaShader.Backend.Glsl.dll" />
    <PackageReference Include="DeltaMaths" />
    <PackageReference Include="DeltaShader.Tool" PrivateAssets="all" />
  </ItemGroup>
</Project>
