<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>DeltaShader.Text</RootNamespace>
    <AssemblyName>DeltaShader.Text</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DeltaShader.Contract\DeltaShader.Contract.csproj" />
    <ProjectReference Include="..\DeltaShader.Abstractions\DeltaShader.Abstractions.csproj" />
    <ProjectReference Include="..\DeltaShader.Analyzers\DeltaShader.Analyzers.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <Analyzer Include="..\DeltaShader.Analyzers\bin\$(Configuration)\netstandard2.0\DeltaShader.Analyzers.dll" />
    <Analyzer Include="..\DeltaShader.Abstractions\bin\$(Configuration)\netstandard2.0\DeltaShader.Abstractions.dll" />
    <Analyzer Include="..\DeltaShader.Compiler\bin\$(Configuration)\netstandard2.0\DeltaShader.Compiler.dll" />
    <Analyzer Include="..\DeltaShader.Backend.Glsl\bin\$(Configuration)\netstandard2.0\DeltaShader.Backend.Glsl.dll" />
    <ProjectReference Include="..\..\..\DeltaMaths\DeltaMaths.csproj">
      <SetTargetFramework>TargetFramework=netstandard2.1</SetTargetFramework>
    </ProjectReference>
  </ItemGroup>
</Project>
