<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Delta.Shader.Tool</RootNamespace>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>glsh</ToolCommandName>
    <NoWarn>$(NoWarn);NU1301</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\\GLSH.Compiler\\GLSH.Compiler.csproj" />
    <ProjectReference Include="..\\GLSH.Backend.Glsl\\GLSH.Backend.Glsl.csproj" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" />
    <PackageReference Include="Microsoft.Build.Locator" />
  </ItemGroup>
</Project>
