<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>GLSH.Compiler</AssemblyName>
    <RootNamespace>DVG.Shaders.Compiler</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\\GLSH.Abstractions\\GLSH.Abstractions.csproj" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" />
  </ItemGroup>
</Project>
