<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Delta.Shader.Compiler.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\\..\\src\\DeltaShader.Compiler\\DeltaShader.Compiler.csproj" />
    <ProjectReference Include="..\\..\\src\\DeltaShader.Analyzers\\DeltaShader.Analyzers.csproj" />
    <ProjectReference Include="..\\..\\src\\DeltaShader.Contract\\DeltaShader.Contract.csproj" />
    <ProjectReference Include="..\\..\\src\\DeltaShader.UI\\DeltaShader.UI.csproj" />
    <ProjectReference Include="..\\..\\..\\DeltaMaths\\src\\DeltaMaths\\DeltaMaths.csproj" />
    <ProjectReference Include="..\\DeltaShader.Compiler.ReferenceFixtures\\DeltaShader.Compiler.ReferenceFixtures.csproj" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" />
    <PackageReference Include="Microsoft.Build.Locator" />
  </ItemGroup>
</Project>
