<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>DeltaShader.Backend.Glsl</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\\DeltaShader.Compiler\\DeltaShader.Compiler.csproj" />
  </ItemGroup>
</Project>
