<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>DVG.Shaders.Compiler.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\\..\\src\\GLSH.Compiler\\GLSH.Compiler.csproj" />
    <ProjectReference Include="..\\..\\..\\Maths\\KibiHex.Maths.csproj" />
    <ProjectReference Include="..\\GLSH.Compiler.ReferenceFixtures\\GLSH.Compiler.ReferenceFixtures.csproj" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" />
    <PackageReference Include="Microsoft.Build.Locator" />
  </ItemGroup>
</Project>
