<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Delta.Shader.Text</RootNamespace>
    <AssemblyName>Delta.Shader.Text</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Delta.Shader.Contract\Delta.Shader.Contract.csproj" />
    <ProjectReference Include="..\Delta.Shader.Abstractions\Delta.Shader.Abstractions.csproj" />
    <ProjectReference Include="..\Delta.Shader.Analyzers\Delta.Shader.Analyzers.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <Analyzer Include="..\Delta.Shader.Analyzers\bin\$(Configuration)\netstandard2.0\Delta.Shader.Analyzers.dll" />
    <Analyzer Include="..\Delta.Shader.Abstractions\bin\$(Configuration)\netstandard2.0\Delta.Shader.Abstractions.dll" />
    <Analyzer Include="..\Delta.Shader.Compiler\bin\$(Configuration)\netstandard2.0\Delta.Shader.Compiler.dll" />
    <Analyzer Include="..\Delta.Shader.Backend.Glsl\bin\$(Configuration)\netstandard2.0\Delta.Shader.Backend.Glsl.dll" />
    <ProjectReference Include="..\..\..\Maths\Delta.Maths.csproj">
      <SetTargetFramework>TargetFramework=netstandard2.1</SetTargetFramework>
    </ProjectReference>
  </ItemGroup>
</Project>
